### ISSUE TITLE
Add the reason why the original project was removed

### ISSUE THREAD

**Issue by mrrfv** [MilosPaunovic/community-faker#2]
Fireship (@codediodeio) [explains](https://www.youtube.com/watch?v=d15DP5zqnYE) what happened with the original project.

**Comment by ondrej-langr** [comment]
Looks like youtube (or author) did not like something that was in the original... as expected. Here's a new link: https://www.youtube.com/watch?v=R6S-b_k-ZKY

But unfortunately this new video does not have the most important stuff and that is the history around it... such a shame.

**Comment by mrrfv** [comment]
The new video only removes the tweet where @Marak talks about how he's barely staying unhomeless and his stuff burned down in an apartment fire.

**Comment by MilosPaunovic** [comment]
As I understand and agree with everything from the video, the whole situation is becoming too political, so that is the reason why I don't think posting the link would be a good idea.

**Comment by TechStudent11** [comment]
@MilosPaunovic Okay then why not post a kind of simplified reason as to why it got removed,

**Comment by MilosPaunovic** [comment]
That is already at the top of README.md, just below the logo:
[https://github.com/MilosPaunovic/community-faker#faq---what-happened-to-the-original-fakerjs](https://github.com/MilosPaunovic/community-faker#faq---what-happened-to-the-original-fakerjs)
